############################################################
# +------------------------------------------------------+ #
# |                       Config                         | #
# +------------------------------------------------------+ #
############################################################

# Additional messages used for debugging.
debug: false

# Webserver used for image generation storage, to use on discord.
webserver:
 # Link to the upload.php file
 upload-url: 'https://domain.net/media/upload.php'
 # Your super secret key, used to validate uploads.
 secret-key: 'AwesomeCoolKey'
 # Main domain
 url: 'https://domain.net/'
 # Additional to url, location of the generated media.
 # Always end with /
 media-location: 'media/generated/'
 
# Save images on the server instead of the webserver?
# If saved locally, change webserver to the server's ip, except upload-url.
save-locally: false

# Location for saving images, if save-locally is true.
# Will always be saved in the plugin folder of "WebServer".
save-location: '/public_html/media/generated/'

# How many days old should the stored files be, before being removed? (In days)
# This only works when 'save-locally' is enabled.
cleanup-age: 7

# Webhook URL from your Discord server.
webhook-url: ''

# Bot picture for events.
server-icon-url: '' # You must provide one for yourself.
server-username: 'Server'

# Replacement for the /say command. /server
console-icon-url: ''
console-username: 'Console'

# Player name formatting.
# Supports PlaceholderAPI if installed.
# DiscordChat Placeholder: %player% - Player's username.
player-username: '%player%'

# Custom join message
custom-join: '&7[&a+&7] %username%'

# Custom leave message
custom-leave: '&7[&c-&7] %username% (%cause%)'
custom-leave-causes:
 another-location:
  keyword: 'You logged in from another location'
  value: 'Disconnect'
 timed-out:
  keyword: 'Timed out'
  value: 'Timed out'
 afk-kick:
  keyword: 'Timed out'
  value: 'Timed out'
 KeepAliveTimeout:
  keyword: 'Internal Exception: io.netty.handler.timeout.ReadTimeoutException'
  value: 'Timed out'
 anti-cheat:
  keyword: 'Unfair Advantage'
  value: 'Cheating?'

############################################################
# +------------------------------------------------------+ #
# |                       Events                         | #
# +------------------------------------------------------+ #
############################################################

server-start: true
server-stop: true
join: true
quit: true
death: true
achievement: true
join-quit-player-count: true

### Chat Event Priority (CaPs)
# HIGH - Event call is of high importance
# HIGHEST - Event call is critical and must have the final say in what happens to the event
# NORMAL - Event call is neither important nor unimportant, and may be run normally
# LOW - Event call is of low importance
# LOWEST - Event call is of very low importance and should be run first, to allow other plugins to further customise the outcome
chat-event-priority: NORMAL

############################################################
# +------------------------------------------------------+ #
# |                 Achievement Filter                   | #
# +------------------------------------------------------+ #
############################################################

#Add here the achievements you want to ignore.
#Each line represents a new message.
#NOTE! You dont need to add the full message!
#The plugin will hide all achievements that contain the text added below.
#  EXAMPLE:
#
#    hide-achievements:
#    - 'Who is Cutting Onions?'

hide-achievements:
- ''
