name: DiscordChat
main: valorless.discordchat.Main
version: version-number
author: Valorless
api-version: 1.18
depend: [ValorlessUtils]
softdepend: [InteractiveChat, Essentials, PlaceholderAPI]
commands:
  discordchat:
    description: Main command.
    usage:
    aliases: [dcm, dc]
  discordchat mute:
    description: Mute discord messages.
    usage:
    aliases: [dcm mute, dc mute]
  server:
    description: /say replacement.
    permission: discordchat.server
    permission-message: Only usable by the console.
permissions:
  discordchat.*:
    description: Gives access to all discordchat commands.
    children:
        discordchat.reload: true
  discordchat.reload:
    description: Allows you to reload the configuration.
    default: op
  