name: DiscordChatMonitor
main: valorless.discordchatmonitor.DiscordChatMonitor
version: 1.3.1.101
author: Valorless
api-version: 1.18
depend: [ValorlessUtils]
softdepend: [LuckPerms, PlaceholderAPI]
commands:
  discordchatmonitor:
    description: Main command.
    usage:
    aliases: dcm
  discordchatmonitor reload:
    description: Reloads the configuration file.
    usage: /dcm reload
    permission: discordchatmonitor.reload
    permission-message: You don't have discordchatmonitor.reload.
    aliases: dcm reload
  server:
    description: /say replacement.
    permission: discordchatmonitor.server
    permission-message: Only usable by the console.
permissions:
  discordchatmonitor.*:
    description: Gives access to all discordchatmonitor commands.
    children:
        discordchatmonitor.reload: true
  discordchatmonitor.reload:
    description: Allows you to reload the configuration.
    default: op
  