name: DiscordChat
main: valorless.discordchat.Main
version: 2.2.0.383
author: Valorless
api-version: 1.18
depend: [ValorlessUtils]
softdepend: [LuckPerms, PlaceholderAPI]
commands:
  discordchat:
    description: Main command.
    usage:
    aliases: [dcm, dc]
  discordchat reload:
    description: Reloads the configuration file.
    usage: /dcm reload
    permission: discordchat.reload
    permission-message: You don't have discordchat.reload.
    aliases: dcm reload
  server:
    description: /say replacement.
    permission: discordchat.server
    permission-message: Only usable by the console.
permissions:
  discordchat.*:
    description: Gives access to all discordchat commands.
    children:
        discordchat.reload: true
  discordchat.reload:
    description: Allows you to reload the configuration.
    default: op
  